<a href="https://colab.research.google.com/github/UmaMaheshwari225a3/DataScience_Task/blob/main/Flipkart_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#importing necessary libraries

In [11]:
import pandas as pd
import numpy as np

Loading the dataset

In [12]:
df= pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/flipkart_sales.csv')
df

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1
...,...,...,...,...,...,...,...,...,...
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

In [13]:
#inbuilt methods of df
df.head()
df.info()
df.describe()
df.shape
# df['Location'].unique() # This line caused the error

# To inspect available columns, you can use:
df.columns
# Or, if you meant to get unique values from a different column, replace 'Location' with an existing column name, for example:
df['Category'].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           1000 non-null   object
 1   Product Name       1000 non-null   object
 2   Category           1000 non-null   object
 3   Price (INR)        1000 non-null   float64
 4   Quantity Sold      1000 non-null   int64
 5   Total Sales (INR)  1000 non-null   float64
 6   Order Date         1000 non-null   object
 7   Payment Method     1000 non-null   object
 8   Customer Rating    1000 non-null   float64
dtypes: float64(3), int64(1), object(5)
memory usage: 70.4+ KB

array(['Books', 'Clothing', 'Beauty', 'Electronics', 'Home & Kitchen'],
      dtype=object)

In [19]:
#Applying boolean filtering on dataframes
#syntax: df[condition]
#1. get data of books cat
df[df['Category']=='Books']
#2. get the records where price > 5000
df[df['Price (INR)']>5000]
#3. smart watch
df[df['Product Name']=='Smartwatch']
#4. prod name where price > 30000 and cust rating atleast 3.0
df.loc[(df['Price (INR)'] > 30000) & (df['Customer Rating'] >= 3.0), 'Product Name']
#5. fetch data of Face cream where price < 20000 and quantity >3
df[(df['Product Name'] == 'Face cream') &
   (df['Price (INR)'] < 20000) &
   (df['Quantity Sold'] > 3)]

Empty DataFrame
Columns: [Order ID, Product Name, Category, Price (INR), Quantity Sold, Total Sales (INR), Order Date, Payment Method, Customer Rating]
Index: []

In [15]:
#Advanaced slicing on df
#1.loc: to slice through multiple cols at the same time
#suntax: df.loc[row_slice,[col1,col2......]]
#df.loc[0:10,['Product Name','Price (INR)']]

#2.iloc: also known as index based slicing
#syntax: df.iloc[row_slice,col_slice]
#note: in case of iloc ending index is exclusive
df.iloc[0:11,0:2]
#1. get data from first 100 rows and even indexed colums
df.iloc[0:100,::2]

#2.get data from product name, price, order date from odd indexed rows
df.iloc[1::2,[1,3,6]]
#3.rev all rowss and cols
df.iloc[::-1,::-1]

,Customer Rating,Payment Method,Order Date,Total Sales (INR),Quantity Sold,Price (INR),Category,Product Name,Order ID
999,1.6,Credit Card,2024-03-26,66792.48,4,16698.12,Home & Kitchen,Table Lamp,ORD01000
998,3.2,Net Banking,2024-10-02,138967.16,4,34741.79,Home & Kitchen,Cookware Set,ORD00999
997,3.1,UPI,2024-07-26,40840.80,1,40840.80,Beauty,Face Cream,ORD00998
996,2.4,Wallet,2024-12-18,65599.02,2,32799.51,Beauty,Perfume,ORD00997
995,5.0,COD,2025-01-13,86987.43,3,28995.81,Electronics,Smartphone,ORD00996
...,...,...,...,...,...,...,...,...,...
4,3.1,UPI,2024-12-27,79770.24,3,26590.08,Home & Kitchen,Cookware Set,ORD00005
3,3.2,Debit Card,2024-11-08,32657.81,1,32657.81,Electronics,Smartwatch,ORD00004
2,4.4,Debit Card,2024-05-18,44368.76,4,11092.19,Beauty,Face Cream,ORD00003
1,3.9,UPI,2024-12-18,51023.40,4,12755.85,Clothing,Jeans,ORD00002
0,3.5,Debit Card,2024-09-12,98139.12,2,49069.56,Books,Educational Book,ORD00001

In [16]:
#Group by: if we want to perform some op based on a category we an use group by
#syntax:
#var = df.groupby('cat_col') -> groups the data
#var.groups -> returns a dict with grouped index
#var1=var.get_group("group_name") -> returns specified group
#categorical col: It consists of less no. of unique values

cat = df.groupby('Category')
cat.groups
beauty = cat.get_group('Beauty')
beauty['Category'].count()
#1.find avg price of clothing cat
clothing = cat.get_group('Clothing')
clothing['Price (INR)'].mean()
#2.find total sales of electronics cat
electronics = cat.get_group('Electronics')
electronics['Total Sales (INR)'].sum()
#3.find total sales for all cat
cat['Total Sales (INR)'].sum()
#4.Find avg price for all prod
df.groupby('Product Name')['Price (INR)'].mean()
#5.find avg rating for all cat
cat['Customer Rating'].mean()
#6.find total sales for all paument methods
df.groupby('Payment Method')['Total Sales (INR)'].sum()
#7.which payment type has max total sales
df.groupby('Payment Method')['Total Sales (INR)'].sum().sort_values(ascending=False).head(1)
#or
df.groupby('Payment Method')['Total Sales (INR)'].sum().idxmax()
#or
pay = df.groupby('Payment Method')['Total Sales (INR)'].sum()
pay = pd.DataFrame(pay)
pay.reset_index(inplace=True)
pay.max()
#8.which product got highest sales
df.groupby('Product Name')['Total Sales (INR)'].sum().sort_values(ascending=False).head(1)

#9.which product got lowest sales
df.groupby('Product Name')['Total Sales (INR)'].sum().sort_values(ascending=True).head(1)
#10.which  prod got sold more
df.groupby('Product Name')['Quantity Sold'].sum().sort_values(ascending=False).head(1)
df.groupby('Product Name')['Quantity Sold'].sum().idxmax()

'Educational Book'